config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards do
    resources :artists
  end

  resources :artists do
    resources :songs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard
  has_many :songs, dependent: :destroy
  validates :name, :genre, presence: true
  # validates :feat_artist, length:{ minimum: 2 }, allow_nil: true
  #need to allow nil for feat_artist
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :artists, dependent: :destroy
  validates :title, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :name, :length, :rank, :albumn, presence: true
  validates :length, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist, only: [:show, :update, :edit, :destroy]
  def index
    @artists = @billboard.artists
  end

  def show
  end

  def new
    @artist = @billboard.artists.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @artist = @billboard.artists.new(artist_params)
    if @artist.save
      redirect_to [@billboard, @artist]
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@billboard, @artist]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to billboard_artists_path(@billboard)
  end

  private 

    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :feat_artist, :genre)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
    @billboard = Billboard.find(params[:id])
  end

  def new
    @billboard = Billboard.new
    render partial: 'form'
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save 
      redirect_to billboards_path
    else
      render :new
    end
  end


  def edit
    @billboard = Billboard.find(params[:id])
    render partial: 'form'
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:title)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [
    :show, :edit, :update, :destroy
  ]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
    render partial: "form"
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to [@artist, @song]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @song.update(song_params)
      redirect_to [@artist, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  private
    def song_params
      params.require(:song).permit(:name, :length, :albumn, :rank)
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for [@billboard, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_area :genre, required: true %>
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Click a Artist To View Songs</h1>
<%= link_to 'Create a new artist', new_billboard_artist_path(@billboard) %>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, [@billboard, artist] %></li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1><%= @billboard.title %> - <%= @artist.name %></h1>
<br />
<%= link_to 'View Songs', artist_songs_path(@artist) %>
<br />
<%= link_to 'Edit Artist', edit_billboard_artist_path([@billboard, @aritst]) %>
<br />
<%= link_to 'Delete Artist', [@billboard, @artist], method: :delete %>
<br />
<%= link_to 'Back To Artists', billboard_artists_path(@billboard) %>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit billboard' : 'Create Billboard' %></h1>

<%= form_for @billboard do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>

  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Click a Billboard to View Content</h1>

<%= link_to 'Create a new Billboard', new_billboard_path %>
<ul>
  <% @billboards.each do |billboard|%>
    <li>
      <%= link_to billboard.title, billboard %>
    </li>
  <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<h1><%= @billboard.title %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View all Billboards', billboards_path %>
<br />
<%= link_to 'View Artists', billboard_artists_path(@billboard) %>
<br />
<%= link_to 'Edit Billboard', edit_billboard_path(@billboard) %>
<br />
<%= link_to 'Delete Billboard', @billboard, method: :delete %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Home: Billboards', billboards_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </div>
</body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :length %>
  <%= f.text_area :length, required: true %>
  <br />
  <%= f.label :albumn %>
  <%= f.text_area :albumn, required: true %>
  <br />
  <%= f.label :rank %>
  <%= f.text_area :rank, required: true %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>All Songs</h1>
<%= link_to 'Create a new song', new_artist_song_path(@artist) %>

<% @songs.each do |song| %>
  <li><%= link_to song.name, [@artist, song] %></li>
<% end %>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1><%= @artist.name %> - <%= @song.name %></h1>
<br />
<%= link_to 'Edit Song', edit_artist_song_path([@artist, @song]) %>
<br />
<%= link_to 'Delete Song', [@artist, @song], method: :delete %>
<br />
<%= link_to 'Back To Songs', artist_songs_path(@artist) %>
<br />